---
nodes: test-nodes
secrets:
  test-secret:
    keyname: "clientid"
    env: "dev"
    source: "azure"
    instance: "kv-zaunic-test"
tasks:
  - name: "Impute Secret"
    action: "generate"
    category: "bash"
    template: "print>secret"
    output: "/>something>secrets_demo.sh"
    